import os

VIRUS_TOTAL_API_KEY = os.getenv("VIRUS_TOTAL_API_KEY", "")

OPEN_PHISH_BASE_URL = os.getenv("OPEN_PHISH_BASE_URL", "")

SAFE_BROWSING_API_KEY = os.getenv("SAFE_BROWSING_API_KEY", "")
SAVE_BROWSING_API_BASE_URL = os.getenv("SAVE_BROWSING_API_BASE_URL", "")

PLAYWRIGHT_WS_URL = os.getenv("PLAYWRIGHT_WS_URL", "")
