# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: safe_browsing_response.proto
# Protobuf Python Version: 5.29.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 1, "", "safe_browsing_response.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1csafe_browsing_response.proto\x12\x1fgoogle.security.safebrowsing.v5"\x98\x01\n\x0e\x46ullHashDetail\x12@\n\x0bthreat_type\x18\x01 \x01(\x0e\x32+.google.security.safebrowsing.v5.ThreatType\x12\x44\n\nattributes\x18\x02 \x03(\x0e\x32\x30.google.security.safebrowsing.v5.ThreatAttribute"i\n\x08\x46ullHash\x12\x11\n\tfull_hash\x18\x01 \x01(\x0c\x12J\n\x11\x66ull_hash_details\x18\x02 \x03(\x0b\x32/.google.security.safebrowsing.v5.FullHashDetail"n\n\x14SafeBrowsingResponse\x12>\n\x0b\x66ull_hashes\x18\x01 \x03(\x0b\x32).google.security.safebrowsing.v5.FullHash\x12\x16\n\x0e\x63\x61\x63he_duration\x18\x02 \x01(\x05*\x8a\x01\n\nThreatType\x12\x1b\n\x17THREAT_TYPE_UNSPECIFIED\x10\x00\x12\x0b\n\x07MALWARE\x10\x01\x12\x16\n\x12SOCIAL_ENGINEERING\x10\x02\x12\x15\n\x11UNWANTED_SOFTWARE\x10\x03\x12#\n\x1fPOTENTIALLY_HARMFUL_APPLICATION\x10\x04*O\n\x0fThreatAttribute\x12 \n\x1cTHREAT_ATTRIBUTE_UNSPECIFIED\x10\x00\x12\n\n\x06\x43\x41NARY\x10\x01\x12\x0e\n\nFRAME_ONLY\x10\x02\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "safe_browsing_response_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_THREATTYPE"]._serialized_start = 440
    _globals["_THREATTYPE"]._serialized_end = 578
    _globals["_THREATATTRIBUTE"]._serialized_start = 580
    _globals["_THREATATTRIBUTE"]._serialized_end = 659
    _globals["_FULLHASHDETAIL"]._serialized_start = 66
    _globals["_FULLHASHDETAIL"]._serialized_end = 218
    _globals["_FULLHASH"]._serialized_start = 220
    _globals["_FULLHASH"]._serialized_end = 325
    _globals["_SAFEBROWSINGRESPONSE"]._serialized_start = 327
    _globals["_SAFEBROWSINGRESPONSE"]._serialized_end = 437
# @@protoc_insertion_point(module_scope)
